version: '3.8'

services:
  aerial-photography-db:
    image: postgis/postgis:15-3.3-alpine
#    build:
#      context: ./../../
#      dockerfile: ./docker/server/db.Dockerfile
    ports:
      - '${DATABASE_PORT}:5432'
    restart: always
    volumes:
      - aerial-photography-db-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro  # Монтирование локального времени
      - /etc/timezone:/etc/timezone:ro
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: "Europe/Moscow"
    networks:
      - network-aerial-photography

  aerial-photography-backend:
    depends_on:
      - aerial-photography-db
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

    env_file:
      - .env
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    build:
      context: .
      dockerfile: backend.Dockerfile
      args:
        BACKEND_PORT: ${BACKEND_PORT}
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      DATABASE_PORT: ${DATABASE_PORT}
      TZ: "Europe/Moscow"
    volumes:
      - ./dependencies:/dependencies
      - /etc/localtime:/etc/localtime:ro  # Монтирование локального времени
      - /etc/timezone:/etc/timezone:ro
    restart: always
    networks:
      - network-aerial-photography

volumes:
  aerial-photography-db-data:

networks:
  network-aerial-photography:
    external: true